<?php
include 'db.php'; include 'audit.php'; header('Content-Type: application/json'); $a=$_GET['action']??'';
function out($d){ echo json_encode($d); exit; }
function is_admin(){ if (session_status()===PHP_SESSION_NONE) session_start(); return !empty($_SESSION['is_admin']); }

if($a==='listUsers'){ $r=$conn->query("SELECT id,name FROM users ORDER BY name"); out($r->fetch_all(MYSQLI_ASSOC)); }
if($a==='listJobTypes'){ $r=$conn->query("SELECT id,name FROM training_job_types ORDER BY name"); out($r->fetch_all(MYSQLI_ASSOC)); }
if($a==='addJobType' && is_admin()){ $name=$conn->real_escape_string($_POST['name']); $conn->query("INSERT INTO training_job_types(name) VALUES('$name')"); audit($conn,'training_job_add','training_job_types',$conn->insert_id,$name); out(['ok'=>true]); }
if($a==='deleteJobType' && is_admin()){ $id=intval($_POST['id']); $chk=$conn->query("SELECT COUNT(*) c FROM training_tasks WHERE job_type_id=$id"); if($chk->fetch_assoc()['c']>0){ out(['ok'=>false,'error'=>'Remove tasks from this job type first.']); } $conn->query("DELETE FROM training_job_types WHERE id=$id"); audit($conn,'training_job_delete','training_job_types',$id,null); out(['ok'=>true]); }
if($a==='listTemplates'){ $job=intval($_GET['job_type_id']); $r=$conn->query("SELECT id,title,description FROM training_tasks WHERE job_type_id=$job ORDER BY id"); out($r->fetch_all(MYSQLI_ASSOC)); }
if($a==='addTemplate' && is_admin()){ $job=intval($_POST['job_type_id']); $title=$conn->real_escape_string($_POST['title']); $desc=$conn->real_escape_string($_POST['description']); $conn->query("INSERT INTO training_tasks(job_type_id,title,description) VALUES($job,'$title','$desc')"); audit($conn,'training_template_add','training_tasks',$conn->insert_id,"job=$job;title=$title"); out(['ok'=>true]); }
if($a==='deleteTemplate' && is_admin()){ $id=intval($_POST['id']); $conn->query("DELETE FROM training_tasks WHERE id=$id"); audit($conn,'training_template_delete','training_tasks',$id,null); out(['ok'=>true]); }
if($a==='assignJobToUser' && is_admin()){ $user=intval($_POST['user_id']); $job=intval($_POST['job_type_id']); $r=$conn->query("SELECT id FROM training_tasks WHERE job_type_id=$job"); $created=0; while($row=$r->fetch_assoc()){ $tid=intval($row['id']); $ex=$conn->query("SELECT id FROM training_assignments WHERE user_id=$user AND training_task_id=$tid"); if(!$ex->num_rows){ $conn->query("INSERT INTO training_assignments(user_id,training_task_id,assigned_at) VALUES($user,$tid,NOW())"); $created++; } } audit($conn,'training_assign_job','user',$user,"job=$job;created=$created"); out(['ok'=>true,'created'=>$created]); }
if($a==='addCustomTask' && is_admin()){ $user=intval($_POST['user_id']); $title=$conn->real_escape_string($_POST['title']); $desc=$conn->real_escape_string($_POST['description']); $conn->query("INSERT INTO custom_training_tasks(user_id,title,description,assigned_at) VALUES($user,'$title','$desc',NOW())"); audit($conn,'training_custom_add','custom_training_tasks',$conn->insert_id,"user=$user;title=$title"); out(['ok'=>true]); }
if($a==='listUserTraining'){ $user=intval($_GET['user_id']); $t=$conn->query("SELECT ta.id,tt.title,tt.description,ta.assigned_at,ta.completed_at,'template' kind FROM training_assignments ta JOIN training_tasks tt ON tt.id=ta.training_task_id WHERE ta.user_id=$user ORDER BY ta.id"); $templ=[]; while($r=$t->fetch_assoc()) $templ[]=$r; $c=$conn->query("SELECT id,title,description,assigned_at,completed_at,'custom' kind FROM custom_training_tasks WHERE user_id=$user ORDER BY id"); $cust=[]; while($r=$c->fetch_assoc()) $cust[]=$r; out(['template'=>$templ,'custom'=>$cust]); }
if($a==='markComplete' && is_admin()){ $id=intval($_POST['assignment_id']); $conn->query("UPDATE training_assignments SET completed_at=NOW() WHERE id=$id"); audit($conn,'training_mark_complete','training_assignments',$id,null); out(['ok'=>true]); }
if($a==='markCompleteCustom' && is_admin()){ $id=intval($_POST['custom_id']); $conn->query("UPDATE custom_training_tasks SET completed_at=NOW() WHERE id=$id"); audit($conn,'training_custom_mark_complete','custom_training_tasks',$id,null); out(['ok'=>true]); }
http_response_code(400); echo json_encode(['error':'Invalid action']);
?>