<?php
include 'db.php'; include 'audit.php'; $a=$_GET['action']??'';
function outj($d){ header('Content-Type: application/json'); echo json_encode($d); exit; }
if($a==='listUsers'){ $r=$conn->query("SELECT id,name FROM users ORDER BY name"); outj($r->fetch_all(MYSQLI_ASSOC)); }
if($a==='getTaskCompletions'){ $s=$_GET['start']??null; $e=$_GET['end']??null; $u=isset($_GET['user_id'])&&$_GET['user_id']!==''?intval($_GET['user_id']):null; $tf=$_GET['timeframe']??null; $w=[]; if($s)$w[]="tc.completed_at>='".$conn->real_escape_string($s)." 00:00:00'"; if($e)$w[]="tc.completed_at<='".$conn->real_escape_string($e)." 23:59:59'"; if($u)$w[]="tc.user_id=$u"; if($tf)$w[]="t.timeframe='".$conn->real_escape_string($tf)."'"; $W=$w?('WHERE '.implode(' AND ',$w)):''; $sql="SELECT tc.completed_at,u.name user_name,t.title,t.timeframe FROM task_completions tc JOIN users u ON u.id=tc.user_id JOIN tasks t ON t.id=tc.task_id $W ORDER BY tc.completed_at DESC"; $r=$conn->query($sql); $rows=[]; while($x=$r->fetch_assoc()) $rows[]=$x; outj($rows); }
if($a==='getTaskCompletionsTimeseries'){ $s=$_GET['start']??date('Y-m-d',strtotime('-30 days')); $e=$_GET['end']??date('Y-m-d'); $u=isset($_GET['user_id'])&&$_GET['user_id']!==''?intval($_GET['user_id']):null; $tf=$_GET['timeframe']??null; $w=["DATE(tc.completed_at) BETWEEN '".$conn->real_escape_string($s)."' AND '".$conn->real_escape_string($e)."'"]; if($u)$w[]="tc.user_id=$u"; if($tf)$w[]="t.timeframe='".$conn->real_escape_string($tf)."'"; $W='WHERE '.implode(' AND ',$w); $r=$conn->query("SELECT DATE(tc.completed_at) d, COUNT(*) c FROM task_completions tc JOIN tasks t ON t.id=tc.task_id $W GROUP BY DATE(tc.completed_at) ORDER BY d"); $rows=[]; while($x=$r->fetch_assoc()) $rows[]=$x; outj($rows); }
if($a==='getTaskUserSummary'){ $s=$_GET['start']??null; $e=$_GET['end']??null; $tf=$_GET['timeframe']??null; $w=[]; if($s)$w[]="tc.completed_at>='".$conn->real_escape_string($s)." 00:00:00'"; if($e)$w[]="tc.completed_at<='".$conn->real_escape_string($e)." 23:59:59'"; if($tf)$w[]="t.timeframe='".$conn->real_escape_string($tf)."'"; $W=$w?('WHERE '.implode(' AND ',$w)):''; $r=$conn->query("SELECT u.name, COUNT(*) total FROM task_completions tc JOIN users u ON u.id=tc.user_id JOIN tasks t ON t.id=tc.task_id $W GROUP BY u.id,u.name ORDER BY total DESC,u.name"); $rows=[]; while($x=$r->fetch_assoc()) $rows[]=$x; outj($rows); }
if($a==='exportTaskUserSummary'){ audit($conn,'export_csv','report',null,'task_user_summary'); header('Content-Type:text/csv'); header('Content-Disposition: attachment; filename="task_user_summary.csv"'); $s=$_GET['start']??null;$e=$_GET['end']??null;$tf=$_GET['timeframe']??null;$w=[];if($s)$w[]="tc.completed_at>='".$conn->real_escape_string($s)." 00:00:00'";if($e)$w[]="tc.completed_at<='".$conn->real_escape_string($e)." 23:59:59'";if($tf)$w[]="t.timeframe='".$conn->real_escape_string($tf)."'";$W=$w?('WHERE '.implode(' AND ',$w)):'';$sql="SELECT u.name, COUNT(*) total FROM task_completions tc JOIN users u ON u.id=tc.user_id JOIN tasks t ON t.id=tc.task_id $W GROUP BY u.id,u.name ORDER BY total DESC,u.name";$out=fopen('php://output','w');fputcsv($out,['User','Total Completions']);$r=$conn->query($sql);while($x=$r->fetch_assoc())fputcsv($out,[$x['name'],$x['total']]);exit; }
if($a==='exportTaskCompletions'){ audit($conn,'export_csv','report',null,'task_completions'); header('Content-Type:text/csv'); header('Content-Disposition: attachment; filename="task_completions.csv"'); $s=$_GET['start']??null;$e=$_GET['end']??null;$u=isset($_GET['user_id'])&&$_GET['user_id']!==''?intval($_GET['user_id']):null;$tf=$_GET['timeframe']??null;$w=[];if($s)$w[]="tc.completed_at>='".$conn->real_escape_string($s)." 00:00:00'";if($e)$w[]="tc.completed_at<='".$conn->real_escape_string($e)." 23:59:59'";if($u)$w[]="tc.user_id=$u";if($tf)$w[]="t.timeframe='".$conn->real_escape_string($tf)."'";$W=$w?('WHERE '.implode(' AND ',$w)):'';$sql="SELECT tc.completed_at,u.name user_name,t.title,t.timeframe FROM task_completions tc JOIN users u ON u.id=tc.user_id JOIN tasks t ON t.id=tc.task_id $W ORDER BY tc.completed_at DESC";$out=fopen('php://output','w');fputcsv($out,['Completed At','User','Task Title','Timeframe']);$r=$conn->query($sql);while($x=$r->fetch_assoc())fputcsv($out,[$x['completed_at'],$x['user_name'],$x['title'],$x['timeframe']]);exit; }
if($a==='listSessions'){ $r=$conn->query("SELECT id,started_at,closed_at,status FROM inventory_counts ORDER BY started_at DESC"); outj($r->fetch_all(MYSQLI_ASSOC)); }
if($a==='listLocations'){ $r=$conn->query("SELECT id,name FROM inventory_locations ORDER BY name"); outj($r->fetch_all(MYSQLI_ASSOC)); }
if($a==='getInventorySnapshot'){ $sid=intval($_GET['session_id']); $loc=intval($_GET['location_id']); $r=$conn->query("SELECT i.name,COALESCE(ie.quantity,0) quantity FROM inventory_items i LEFT JOIN inventory_entries ie ON ie.item_id=i.id AND ie.count_id=$sid WHERE i.location_id=$loc ORDER BY i.name"); $rows=[]; while($x=$r->fetch_assoc()) $rows[]=$x; outj($rows); }
if($a==='exportInventorySnapshot'){ audit($conn,'export_csv','report',null,'inventory_snapshot'); header('Content-Type:text/csv'); header('Content-Disposition: attachment; filename="inventory_snapshot.csv"'); $sid=intval($_GET['session_id']); $loc=intval($_GET['location_id']); $r=$conn->query("SELECT i.name,COALESCE(ie.quantity,0) quantity FROM inventory_items i LEFT JOIN inventory_entries ie ON ie.item_id=i.id AND ie.count_id=$sid WHERE i.location_id=$loc ORDER BY i.name"); $out=fopen('php://output','w'); fputcsv($out,['Item','Quantity']); while($x=$r->fetch_assoc()) fputcsv($out,[$x['name'],$x['quantity']]); exit; }
if($a==='exportAllInventorySessions'){ audit($conn,'export_csv','report',null,'inventory_all_sessions'); header('Content-Type:text/csv'); header('Content-Disposition: attachment; filename="inventory_all_sessions.csv"'); $loc=isset($_GET['location_id'])&&$_GET['location_id']!==''?intval($_GET['location_id']):null; $W=$loc?"WHERE i.location_id=$loc":''; $sql="SELECT ic.id session_id,ic.started_at,ic.closed_at,i.name item,l.name location,COALESCE(ie.quantity,0) quantity FROM inventory_counts ic LEFT JOIN inventory_entries ie ON ie.count_id=ic.id LEFT JOIN inventory_items i ON i.id=ie.item_id LEFT JOIN inventory_locations l ON l.id=i.location_id $W ORDER BY ic.id,l.name,i.name"; $out=fopen('php://output','w'); fputcsv($out,['Session ID','Started','Closed','Location','Item','Quantity']); $r=$conn->query($sql); while($x=$r->fetch_assoc()) fputcsv($out,[$x['session_id'],$x['started_at'],$x['closed'],$x['location'],$x['item'],$x['quantity']]); exit; }
http_response_code(400); echo 'Invalid action';
?>