-- tasktracker_full_system.sql
CREATE DATABASE IF NOT EXISTS tasktracker CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE tasktracker;
CREATE TABLE IF NOT EXISTS users (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100) NOT NULL, role ENUM('admin','user') DEFAULT 'user');
CREATE TABLE IF NOT EXISTS tasks (id INT AUTO_INCREMENT PRIMARY KEY, title VARCHAR(255) NOT NULL, description TEXT, timeframe ENUM('Morning','Mid-Day','Afternoon'), type ENUM('single','daily','weekly','monthly'), start_date DATE, end_date DATE NULL, created_by INT NULL);
CREATE TABLE IF NOT EXISTS task_completions (id INT AUTO_INCREMENT PRIMARY KEY, task_id INT, user_id INT, completed_at DATETIME DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE CASCADE, FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS doc_categories (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(255) NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS docs (id INT AUTO_INCREMENT PRIMARY KEY, title VARCHAR(255) NOT NULL, content LONGTEXT, category_id INT NOT NULL, FOREIGN KEY (category_id) REFERENCES doc_categories(id) ON DELETE RESTRICT);
CREATE TABLE IF NOT EXISTS inventory_locations (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(255) NOT NULL);
CREATE TABLE IF NOT EXISTS inventory_items (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(255) NOT NULL, location_id INT NOT NULL, FOREIGN KEY (location_id) REFERENCES inventory_locations(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS inventory_counts (id INT AUTO_INCREMENT PRIMARY KEY, started_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, closed_at DATETIME NULL, status ENUM('open','closed') NOT NULL DEFAULT 'open');
CREATE TABLE IF NOT EXISTS inventory_entries (id INT AUTO_INCREMENT PRIMARY KEY, count_id INT NOT NULL, item_id INT NOT NULL, quantity INT NOT NULL, FOREIGN KEY (count_id) REFERENCES inventory_counts(id) ON DELETE CASCADE, FOREIGN KEY (item_id) REFERENCES inventory_items(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS training_job_types (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(255) NOT NULL);
CREATE TABLE IF NOT EXISTS training_tasks (id INT AUTO_INCREMENT PRIMARY KEY, job_type_id INT NOT NULL, title VARCHAR(255) NOT NULL, description TEXT, FOREIGN KEY (job_type_id) REFERENCES training_job_types(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS training_assignments (id INT AUTO_INCREMENT PRIMARY KEY, user_id INT NOT NULL, training_task_id INT NOT NULL, assigned_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, completed_at DATETIME DEFAULT NULL, FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE, FOREIGN KEY (training_task_id) REFERENCES training_tasks(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS custom_training_tasks (id INT AUTO_INCREMENT PRIMARY KEY, user_id INT NOT NULL, title VARCHAR(255) NOT NULL, description TEXT, assigned_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, completed_at DATETIME DEFAULT NULL, FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE);
INSERT INTO users (name, role) VALUES ('Admin', 'admin') ON DUPLICATE KEY UPDATE name=name;
